# Generated by Django 5.0.1 on 2025-10-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='총괄담당자가 승인한 직원만 시스템 사용 가능', verbose_name='승인 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '총괄담당자'), ('manager', '담당자')], default='manager', max_length=20, verbose_name='직급'),
        ),
    ]
