# Generated by Django 5.0.1 on 2025-10-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='연락처'),
        ),
    ]
