# Generated by Django 5.0.1 on 2025-10-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_traveler_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='first_name_kr',
            field=models.CharField(max_length=10, verbose_name='한글 이름'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name_kr',
            field=models.CharField(max_length=10, verbose_name='한글 성'),
        ),
    ]
