# Generated by Django 5.0.1 on 2025-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_traveler_first_name_kr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='first_name_kr',
            field=models.CharField(max_length=20, verbose_name='한글 이름'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name_kr',
            field=models.CharField(max_length=20, verbose_name='한글 성'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_kr',
            field=models.CharField(blank=True, max_length=20, verbose_name='한글 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_kr',
            field=models.CharField(blank=True, max_length=20, verbose_name='한글 성'),
        ),
    ]
