
"""trips 앱의 여행 생성 API가 다양한 현실 시나리오를 처리하는지 검증한다."""

from datetime import date, timedelta
from decimal import Decimal

import pytest
from rest_framework.test import APIClient


TRIP_CREATION_SCENARIOS = [
    {
        "title_suffix": "01",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 57,
        "heart_rate_max": 113,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5611", "lng": "126.9711", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 1",
    },
    {
        "title_suffix": "02",
        "start_offset": 3,
        "duration_days": 4,
        "heart_rate_min": 59,
        "heart_rate_max": 116,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5622", "lng": "126.9722", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 2",
    },
    {
        "title_suffix": "03",
        "start_offset": 4,
        "duration_days": 2,
        "heart_rate_min": 61,
        "heart_rate_max": 119,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 3",
    },
    {
        "title_suffix": "04",
        "start_offset": 5,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 122,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5644", "lng": "126.9741", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 4",
    },
    {
        "title_suffix": "05",
        "start_offset": 6,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 110,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5605", "lng": "126.9752", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 5",
    },
    {
        "title_suffix": "06",
        "start_offset": 7,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 113,
        "spo2_min": "95.5",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 6",
    },
    {
        "title_suffix": "07",
        "start_offset": 1,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 116,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5621", "lng": "126.9721", "radius": "2.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 7",
    },
    {
        "title_suffix": "08",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 119,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5632", "lng": "126.9732", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 8",
    },
    {
        "title_suffix": "09",
        "start_offset": 3,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 122,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 9",
    },
    {
        "title_suffix": "10",
        "start_offset": 4,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 110,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5654", "lng": "126.9754", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 10",
    },
    {
        "title_suffix": "11",
        "start_offset": 5,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 113,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5615", "lng": "126.9715", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 11",
    },
    {
        "title_suffix": "12",
        "start_offset": 6,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 116,
        "spo2_min": "95.5",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 12",
    },
    {
        "title_suffix": "13",
        "start_offset": 7,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 119,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5636", "lng": "126.9736", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 13",
    },
    {
        "title_suffix": "14",
        "start_offset": 1,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 122,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5647", "lng": "126.9747", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 14",
    },
    {
        "title_suffix": "15",
        "start_offset": 2,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 110,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 15",
    },
    {
        "title_suffix": "16",
        "start_offset": 3,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 113,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5628", "lng": "126.9728", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 16",
    },
    {
        "title_suffix": "17",
        "start_offset": 4,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 116,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5639", "lng": "126.9739", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 17",
    },
    {
        "title_suffix": "18",
        "start_offset": 5,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 119,
        "spo2_min": "95.5",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 18",
    },
    {
        "title_suffix": "19",
        "start_offset": 6,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 122,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5651", "lng": "126.9751", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 19",
    },
    {
        "title_suffix": "20",
        "start_offset": 7,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 110,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5612", "lng": "126.9712", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 20",
    },
    {
        "title_suffix": "21",
        "start_offset": 1,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 113,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 21",
    },
    {
        "title_suffix": "22",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 116,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5633", "lng": "126.9733", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 22",
    },
    {
        "title_suffix": "23",
        "start_offset": 3,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 119,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5644", "lng": "126.9744", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 23",
    },
    {
        "title_suffix": "24",
        "start_offset": 4,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 122,
        "spo2_min": "95.5",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 24",
    },
    {
        "title_suffix": "25",
        "start_offset": 5,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 110,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5655", "lng": "126.9755", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 25",
    },
    {
        "title_suffix": "26",
        "start_offset": 6,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 113,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5616", "lng": "126.9716", "radius": "1.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 26",
    },
    {
        "title_suffix": "27",
        "start_offset": 7,
        "duration_days": 4,
        "heart_rate_min": 61,
        "heart_rate_max": 116,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 27",
    },
    {
        "title_suffix": "28",
        "start_offset": 1,
        "duration_days": 3,
        "heart_rate_min": 55,
        "heart_rate_max": 119,
        "spo2_min": "95.5",
        "geofence": {"lat": "37.5627", "lng": "126.9727", "radius": "1.5"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 28",
    },
    {
        "title_suffix": "29",
        "start_offset": 2,
        "duration_days": 4,
        "heart_rate_min": 57,
        "heart_rate_max": 122,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5638", "lng": "126.9738", "radius": "2.0"},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 29",
    },
    {
        "title_suffix": "30",
        "start_offset": 3,
        "duration_days": 3,
        "heart_rate_min": 59,
        "heart_rate_max": 110,
        "spo2_min": "95.5",
        "geofence": {"lat": None, "lng": None, "radius": None},
        "expected_status": 201,
        "issue": "정상 여행 생성 시나리오 30",
    },
    {
        "title_suffix": "D31",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D32",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D33",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D34",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D35",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D36",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D37",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D38",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D39",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "D40",
        "start_offset": 1,
        "duration_days": -1,
        "heart_rate_min": 60,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "종료일이 시작일보다 빠른 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "종료일은 시작일보다 빠를 수 없습니다.",
    },
    {
        "title_suffix": "G41",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 58,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": "126.9780", "radius": "1.2"},
        "expected_status": 400,
        "issue": "지오펜스 일부만 입력된 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "지오펜스를 사용하려면 위도/경도/반경을 모두 입력해야 합니다.",
    },
    {
        "title_suffix": "G42",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 58,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5650", "lng": None, "radius": "1.2"},
        "expected_status": 400,
        "issue": "지오펜스 일부만 입력된 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "지오펜스를 사용하려면 위도/경도/반경을 모두 입력해야 합니다.",
    },
    {
        "title_suffix": "G43",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 58,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": None, "lng": None, "radius": "1.2"},
        "expected_status": 400,
        "issue": "지오펜스 일부만 입력된 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "지오펜스를 사용하려면 위도/경도/반경을 모두 입력해야 합니다.",
    },
    {
        "title_suffix": "G44",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 58,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5650", "lng": "126.9780", "radius": None},
        "expected_status": 400,
        "issue": "지오펜스 일부만 입력된 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "지오펜스를 사용하려면 위도/경도/반경을 모두 입력해야 합니다.",
    },
    {
        "title_suffix": "G45",
        "start_offset": 2,
        "duration_days": 3,
        "heart_rate_min": 58,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5650", "lng": None, "radius": None},
        "expected_status": 400,
        "issue": "지오펜스 일부만 입력된 요청",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "지오펜스를 사용하려면 위도/경도/반경을 모두 입력해야 합니다.",
    },
    {
        "title_suffix": "H46",
        "start_offset": 3,
        "duration_days": 2,
        "heart_rate_min": 130,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "심박수 최소/최대 범위 역전",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "최소 심박수는 최대 심박수보다 작거나 같아야 합니다.",
    },
    {
        "title_suffix": "H47",
        "start_offset": 3,
        "duration_days": 2,
        "heart_rate_min": 130,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "심박수 최소/최대 범위 역전",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "최소 심박수는 최대 심박수보다 작거나 같아야 합니다.",
    },
    {
        "title_suffix": "H48",
        "start_offset": 3,
        "duration_days": 2,
        "heart_rate_min": 130,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "심박수 최소/최대 범위 역전",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "최소 심박수는 최대 심박수보다 작거나 같아야 합니다.",
    },
    {
        "title_suffix": "H49",
        "start_offset": 3,
        "duration_days": 2,
        "heart_rate_min": 130,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "심박수 최소/최대 범위 역전",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "최소 심박수는 최대 심박수보다 작거나 같아야 합니다.",
    },
    {
        "title_suffix": "H50",
        "start_offset": 3,
        "duration_days": 2,
        "heart_rate_min": 130,
        "heart_rate_max": 120,
        "spo2_min": "94.0",
        "geofence": {"lat": "37.5665", "lng": "126.9780", "radius": "1.5"},
        "expected_status": 400,
        "issue": "심박수 최소/최대 범위 역전",
        "expected_error_field": "non_field_errors",
        "expected_error_message": "최소 심박수는 최대 심박수보다 작거나 같아야 합니다.",
    },
]


@pytest.mark.parametrize("scenario", TRIP_CREATION_SCENARIOS)
@pytest.mark.django_db
def test_trip_creation_covers_realistic_variations(manager_user, scenario):
    """여행 생성 시 다양한 임계치·날짜 조합에서 기대 동작을 확인한다."""

    client = APIClient()
    login = client.post(
        "/api/auth/login/",
        data={"username": manager_user.username, "password": "secure-password"},
        format="json",
    )
    assert login.status_code == 200

    start_date = date.today() + timedelta(days=scenario["start_offset"])
    end_date = start_date + timedelta(days=scenario["duration_days"])

    payload = {
        "title": f"품질 검사 여행 {scenario['title_suffix']}",
        "destination": "서울",
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
        "heart_rate_min": scenario["heart_rate_min"],
        "heart_rate_max": scenario["heart_rate_max"],
        "spo2_min": scenario["spo2_min"],
    }

    geofence = scenario["geofence"]
    if geofence["lat"] is not None:
        payload["geofence_center_lat"] = geofence["lat"]
    if geofence["lng"] is not None:
        payload["geofence_center_lng"] = geofence["lng"]
    if geofence["radius"] is not None:
        payload["geofence_radius_km"] = geofence["radius"]

    create_response = client.post("/api/trips/", data=payload, format="json")
    assert create_response.status_code == scenario["expected_status"], scenario["issue"]

    if create_response.status_code != 201:
        error_field = scenario["expected_error_field"]
        assert error_field in create_response.data
        if scenario.get("expected_error_message"):
            messages = create_response.data[error_field]
            if isinstance(messages, list):
                assert scenario["expected_error_message"] in messages[0]
            else:
                assert scenario["expected_error_message"] in str(messages)
        return

    body = create_response.data
    assert body["manager"] == manager_user.id
    assert body["participant_count"] == 0
    assert body["title"].endswith(scenario["title_suffix"])

    if geofence["lat"] is None:
        assert body["geofence_center_lat"] is None
        assert body["geofence_center_lng"] is None
        assert body["geofence_radius_km"] is None
    else:
        assert Decimal(str(body["geofence_center_lat"])) == Decimal(str(geofence["lat"]))
        assert Decimal(str(body["geofence_center_lng"])) == Decimal(str(geofence["lng"]))
        assert Decimal(str(body["geofence_radius_km"])) == Decimal(str(geofence["radius"]))