# Generated by Django 5.0.1 on 2025-10-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0003_trip_geofence_center_lat_trip_geofence_center_lng_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="데이터가 측정된 시각 (UTC 기준으로 저장).",
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveIntegerField(
                        help_text="분당 심박수. 보통 40~180 사이의 값을 예상합니다."
                    ),
                ),
                (
                    "spo2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="산소포화도(%). 소수점 둘째 자리까지 보관합니다.",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="normal",
                        help_text="서버에서 판정한 상태값 (예: normal, caution, danger).",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="레코드가 DB에 삽입된 시각."
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="어떤 참가자의 측정값인지 지정합니다.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="trips.tripparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "건강 스냅샷",
                "verbose_name_plural": "건강 스냅샷 목록",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(
                        db_index=True, help_text="위치가 기록된 시각."
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="위도. 소수점 6자리면 약 0.11m 해상도를 제공합니다.",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="경도. 소수점 6자리로 대부분의 도시 지역을 커버합니다.",
                        max_digits=9,
                    ),
                ),
                (
                    "accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="위치 정확도(미터). 없으면 기기에서 값을 주지 않은 것입니다.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="좌표를 측정한 참가자.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_snapshots",
                        to="trips.tripparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "위치 스냅샷",
                "verbose_name_plural": "위치 스냅샷 목록",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("health", "건강 이상"), ("location", "위치 이탈")],
                        help_text="경보 분류 (건강/위치).",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="관리자에게 보여줄 경보 요약 메시지."),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(help_text="경보 판단에 사용한 측정 시각."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="경보가 발생한 참가자.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_alerts",
                        to="trips.tripparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "모니터링 경보",
                "verbose_name_plural": "모니터링 경보 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]