"""users 앱 핵심 인증 플로우를 다양한 현실 시나리오로 검증하는 통합 테스트."""

import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient


STAFF_REGISTRATION_SCENARIOS = [
    {
        "username": "staff01",
        "password": "StaffPass101!",
        "email": "staff01@example.com",
        "phone": "010-1201-4501",
        "first_name": "Case1",
        "last_name": "Manager",
        "first_name_kr": "케이스1",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 1",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff02",
        "password": "StaffPass102!",
        "email": "staff02@example.com",
        "phone": "010-1202-4502",
        "first_name": "Case2",
        "last_name": "Manager",
        "first_name_kr": "케이스2",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 2",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff03",
        "password": "StaffPass103!",
        "email": "staff03@example.com",
        "phone": "010-1203-4503",
        "first_name": "Case3",
        "last_name": "Manager",
        "first_name_kr": "케이스3",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 3",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff04",
        "password": "StaffPass104!",
        "email": "staff04@example.com",
        "phone": "010-1204-4504",
        "first_name": "Case4",
        "last_name": "Manager",
        "first_name_kr": "케이스4",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 4",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff05",
        "password": "StaffPass105!",
        "email": "staff05@example.com",
        "phone": "010-1205-4505",
        "first_name": "Case5",
        "last_name": "Manager",
        "first_name_kr": "케이스5",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 5",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff06",
        "password": "StaffPass106!",
        "email": "staff06@example.com",
        "phone": "010-1206-4506",
        "first_name": "Case6",
        "last_name": "Manager",
        "first_name_kr": "케이스6",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 6",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": True,
    },
    {
        "username": "staff07",
        "password": "StaffPass107!",
        "email": "staff07@example.com",
        "phone": "010-1207-4507",
        "first_name": "Case7",
        "last_name": "Manager",
        "first_name_kr": "케이스7",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 7",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff08",
        "password": "StaffPass108!",
        "email": "staff08@example.com",
        "phone": "010-1208-4508",
        "first_name": "Case8",
        "last_name": "Manager",
        "first_name_kr": "케이스8",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 8",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff09",
        "password": "StaffPass109!",
        "email": "staff09@example.com",
        "phone": "010-1209-4509",
        "first_name": "Case9",
        "last_name": "Manager",
        "first_name_kr": "케이스9",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 9",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff10",
        "password": "StaffPass110!",
        "email": "staff10@example.com",
        "phone": "010-1210-4510",
        "first_name": "Case10",
        "last_name": "Manager",
        "first_name_kr": "케이스10",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 10",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff11",
        "password": "StaffPass111!",
        "email": "staff11@example.com",
        "phone": "010-1211-4511",
        "first_name": "Case11",
        "last_name": "Manager",
        "first_name_kr": "케이스11",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 11",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff12",
        "password": "StaffPass112!",
        "email": "staff12@example.com",
        "phone": "010-1212-4512",
        "first_name": "Case12",
        "last_name": "Manager",
        "first_name_kr": "케이스12",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 12",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff13",
        "password": "StaffPass113!",
        "email": "staff13@example.com",
        "phone": "010-1213-4513",
        "first_name": "Case13",
        "last_name": "Manager",
        "first_name_kr": "케이스13",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 13",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff14",
        "password": "StaffPass114!",
        "email": "staff14@example.com",
        "phone": "010-1214-4514",
        "first_name": "Case14",
        "last_name": "Manager",
        "first_name_kr": "케이스14",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 14",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff15",
        "password": "StaffPass115!",
        "email": "staff15@example.com",
        "phone": "010-1215-4515",
        "first_name": "Case15",
        "last_name": "Manager",
        "first_name_kr": "케이스15",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 15",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff16",
        "password": "StaffPass116!",
        "email": "staff16@example.com",
        "phone": "010-1216-4516",
        "first_name": "Case16",
        "last_name": "Manager",
        "first_name_kr": "케이스16",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 16",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": True,
    },
    {
        "username": "staff17",
        "password": "StaffPass117!",
        "email": "staff17@example.com",
        "phone": "010-1217-4517",
        "first_name": "Case17",
        "last_name": "Manager",
        "first_name_kr": "케이스17",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 17",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff18",
        "password": "StaffPass118!",
        "email": "staff18@example.com",
        "phone": "010-1218-4518",
        "first_name": "Case18",
        "last_name": "Manager",
        "first_name_kr": "케이스18",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 18",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff19",
        "password": "StaffPass119!",
        "email": "staff19@example.com",
        "phone": "010-1219-4519",
        "first_name": "Case19",
        "last_name": "Manager",
        "first_name_kr": "케이스19",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 19",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff20",
        "password": "StaffPass120!",
        "email": "staff20@example.com",
        "phone": "010-1220-4520",
        "first_name": "Case20",
        "last_name": "Manager",
        "first_name_kr": "케이스20",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 20",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff21",
        "password": "StaffPass121!",
        "email": "staff21@example.com",
        "phone": "010-1221-4521",
        "first_name": "Case21",
        "last_name": "Manager",
        "first_name_kr": "케이스21",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 21",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff22",
        "password": "StaffPass122!",
        "email": "staff22@example.com",
        "phone": "010-1222-4522",
        "first_name": "Case22",
        "last_name": "Manager",
        "first_name_kr": "케이스22",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 22",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff23",
        "password": "StaffPass123!",
        "email": "staff23@example.com",
        "phone": "010-1223-4523",
        "first_name": "Case23",
        "last_name": "Manager",
        "first_name_kr": "케이스23",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 23",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff24",
        "password": "StaffPass124!",
        "email": "staff24@example.com",
        "phone": "010-1224-4524",
        "first_name": "Case24",
        "last_name": "Manager",
        "first_name_kr": "케이스24",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 24",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff25",
        "password": "StaffPass125!",
        "email": "staff25@example.com",
        "phone": "010-1225-4525",
        "first_name": "Case25",
        "last_name": "Manager",
        "first_name_kr": "케이스25",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 25",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": True,
    },
    {
        "username": "staff26",
        "password": "StaffPass126!",
        "email": "staff26@example.com",
        "phone": "010-1226-4526",
        "first_name": "Case26",
        "last_name": "Manager",
        "first_name_kr": "케이스26",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 26",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff27",
        "password": "StaffPass127!",
        "email": "staff27@example.com",
        "phone": "010-1227-4527",
        "first_name": "Case27",
        "last_name": "Manager",
        "first_name_kr": "케이스27",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 27",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff28",
        "password": "StaffPass128!",
        "email": "staff28@example.com",
        "phone": "010-1228-4528",
        "first_name": "Case28",
        "last_name": "Manager",
        "first_name_kr": "케이스28",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 28",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff29",
        "password": "StaffPass129!",
        "email": "staff29@example.com",
        "phone": "010-1229-4529",
        "first_name": "Case29",
        "last_name": "Manager",
        "first_name_kr": "케이스29",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 29",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "staff30",
        "password": "StaffPass130!",
        "email": "staff30@example.com",
        "phone": "010-1230-4530",
        "first_name": "Case30",
        "last_name": "Manager",
        "first_name_kr": "케이스30",
        "last_name_kr": "담당",
        "role": "manager",
        "expected_status": 201,
        "issue": "정상 신규 등록 시나리오 30",
        "attempt_login_before_approval": True,
        "wrong_password_attempt": False,
    },
    {
        "username": "weakpass31",
        "password": "weak",
        "email": "weak31@example.com",
        "phone": "010-5531-8831",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass32",
        "password": "weak",
        "email": "weak32@example.com",
        "phone": "010-5532-8832",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass33",
        "password": "weak",
        "email": "weak33@example.com",
        "phone": "010-5533-8833",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass34",
        "password": "weak",
        "email": "weak34@example.com",
        "phone": "010-5534-8834",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass35",
        "password": "weak",
        "email": "weak35@example.com",
        "phone": "010-5535-8835",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass36",
        "password": "weak",
        "email": "weak36@example.com",
        "phone": "010-5536-8836",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass37",
        "password": "weak",
        "email": "weak37@example.com",
        "phone": "010-5537-8837",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass38",
        "password": "weak",
        "email": "weak38@example.com",
        "phone": "010-5538-8838",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass39",
        "password": "weak",
        "email": "weak39@example.com",
        "phone": "010-5539-8839",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "weakpass40",
        "password": "weak",
        "email": "weak40@example.com",
        "phone": "010-5540-8840",
        "first_name": "Weak",
        "last_name": "Password",
        "first_name_kr": "약한",
        "last_name_kr": "비번",
        "role": "manager",
        "expected_status": 400,
        "issue": "비밀번호 길이 부족",
        "expected_error_field": "password",
    },
    {
        "username": "invalidmail41",
        "password": "ValidPass41!!",
        "email": "invalid-mail-41",
        "phone": "010-7741-3341",
        "first_name": "Invalid",
        "last_name": "Email",
        "first_name_kr": "잘못된",
        "last_name_kr": "이메일",
        "role": "manager",
        "expected_status": 400,
        "issue": "이메일 형식 오류",
        "expected_error_field": "email",
    },
    {
        "username": "invalidmail42",
        "password": "ValidPass42!!",
        "email": "invalid-mail-42",
        "phone": "010-7742-3342",
        "first_name": "Invalid",
        "last_name": "Email",
        "first_name_kr": "잘못된",
        "last_name_kr": "이메일",
        "role": "manager",
        "expected_status": 400,
        "issue": "이메일 형식 오류",
        "expected_error_field": "email",
    },
    {
        "username": "invalidmail43",
        "password": "ValidPass43!!",
        "email": "invalid-mail-43",
        "phone": "010-7743-3343",
        "first_name": "Invalid",
        "last_name": "Email",
        "first_name_kr": "잘못된",
        "last_name_kr": "이메일",
        "role": "manager",
        "expected_status": 400,
        "issue": "이메일 형식 오류",
        "expected_error_field": "email",
    },
    {
        "username": "invalidmail44",
        "password": "ValidPass44!!",
        "email": "invalid-mail-44",
        "phone": "010-7744-3344",
        "first_name": "Invalid",
        "last_name": "Email",
        "first_name_kr": "잘못된",
        "last_name_kr": "이메일",
        "role": "manager",
        "expected_status": 400,
        "issue": "이메일 형식 오류",
        "expected_error_field": "email",
    },
    {
        "username": "invalidmail45",
        "password": "ValidPass45!!",
        "email": "invalid-mail-45",
        "phone": "010-7745-3345",
        "first_name": "Invalid",
        "last_name": "Email",
        "first_name_kr": "잘못된",
        "last_name_kr": "이메일",
        "role": "manager",
        "expected_status": 400,
        "issue": "이메일 형식 오류",
        "expected_error_field": "email",
    },
    {
        "username": "duplicate46",
        "password": "DupPass46!!",
        "email": "duplicate46@example.com",
        "phone": "010-9046-4046",
        "first_name": "Duplicate",
        "last_name": "User",
        "first_name_kr": "중복",
        "last_name_kr": "사용자",
        "role": "manager",
        "expected_status": 400,
        "issue": "이미 등록된 사용자 이름",
        "expected_error_field": "username",
        "preexisting": "username",
    },
    {
        "username": "duplicate47",
        "password": "DupPass47!!",
        "email": "duplicate47@example.com",
        "phone": "010-9047-4047",
        "first_name": "Duplicate",
        "last_name": "User",
        "first_name_kr": "중복",
        "last_name_kr": "사용자",
        "role": "manager",
        "expected_status": 400,
        "issue": "이미 등록된 사용자 이름",
        "expected_error_field": "username",
        "preexisting": "username",
    },
    {
        "username": "duplicate48",
        "password": "DupPass48!!",
        "email": "duplicate48@example.com",
        "phone": "010-9048-4048",
        "first_name": "Duplicate",
        "last_name": "User",
        "first_name_kr": "중복",
        "last_name_kr": "사용자",
        "role": "manager",
        "expected_status": 400,
        "issue": "이미 등록된 사용자 이름",
        "expected_error_field": "username",
        "preexisting": "username",
    },
    {
        "username": "duplicate49",
        "password": "DupPass49!!",
        "email": "duplicate49@example.com",
        "phone": "010-9049-4049",
        "first_name": "Duplicate",
        "last_name": "User",
        "first_name_kr": "중복",
        "last_name_kr": "사용자",
        "role": "manager",
        "expected_status": 400,
        "issue": "이미 등록된 사용자 이름",
        "expected_error_field": "username",
        "preexisting": "username",
    },
    {
        "username": "duplicate50",
        "password": "DupPass50!!",
        "email": "duplicate50@example.com",
        "phone": "010-9050-4050",
        "first_name": "Duplicate",
        "last_name": "User",
        "first_name_kr": "중복",
        "last_name_kr": "사용자",
        "role": "manager",
        "expected_status": 400,
        "issue": "이미 등록된 사용자 이름",
        "expected_error_field": "username",
        "preexisting": "username",
    },
]


@pytest.mark.parametrize("scenario", STAFF_REGISTRATION_SCENARIOS)
@pytest.mark.django_db
def test_staff_registration_quality_across_edge_cases(scenario):
    """각 시나리오에 맞춰 회원가입·승인·로그인 흐름을 검증한다."""

    User = get_user_model()
    super_admin = User.objects.create_user(
        username="superadmin",
        password="AdminPass123!",
        email="superadmin@example.com",
        role="super_admin",
        is_approved=True,
        is_staff=True,
        is_superuser=True,
        first_name="Super",
        last_name="Admin",
        first_name_kr="관리자",
        last_name_kr="최고",
    )

    if scenario.get("preexisting") == "username":
        User.objects.create_user(
            username=scenario["username"],
            password="ExistingPass123!",
            email=f"existing-{scenario['username']}@example.com",
            role="manager",
            is_approved=True,
        )
    elif scenario.get("preexisting") == "email":
        User.objects.create_user(
            username=f"other-{scenario['username']}",
            password="ExistingPass123!",
            email=scenario["email"],
            role="manager",
            is_approved=True,
        )

    registration_payload = {
        "username": scenario["username"],
        "password": scenario["password"],
        "email": scenario["email"],
        "phone": scenario["phone"],
        "first_name": scenario["first_name"],
        "last_name": scenario["last_name"],
        "first_name_kr": scenario["first_name_kr"],
        "last_name_kr": scenario["last_name_kr"],
        "role": scenario["role"],
    }

    anonymous_client = APIClient()
    register_response = anonymous_client.post(
        "/api/auth/register/",
        data=registration_payload,
        format="json",
    )

    assert register_response.status_code == scenario["expected_status"], scenario["issue"]

    if scenario["expected_status"] != 201:
        error_field = scenario["expected_error_field"]
        assert error_field in register_response.data
        return

    staff_id = register_response.data["id"]
    staff_username = register_response.data["username"]

    if scenario.get("attempt_login_before_approval"):
        before_client = APIClient()
        before_login = before_client.post(
            "/api/auth/login/",
            data={"username": staff_username, "password": scenario["password"]},
            format="json",
        )
        assert before_login.status_code == 403

    admin_client = APIClient()
    admin_login = admin_client.post(
        "/api/auth/login/",
        data={"username": super_admin.username, "password": "AdminPass123!"},
        format="json",
    )
    assert admin_login.status_code == 200

    approve_response = admin_client.post(f"/api/auth/staff/{staff_id}/approve/")
    assert approve_response.status_code == 200
    assert approve_response.data["user"]["is_approved"] is True

    if scenario.get("wrong_password_attempt"):
        wrong_client = APIClient()
        wrong_login = wrong_client.post(
            "/api/auth/login/",
            data={"username": staff_username, "password": "WrongPass123!"},
            format="json",
        )
        assert wrong_login.status_code == 401

    final_client = APIClient()
    final_login = final_client.post(
        "/api/auth/login/",
        data={"username": staff_username, "password": scenario["password"]},
        format="json",
    )
    assert final_login.status_code == 200
    assert final_login.data["is_approved"] is True

    profile_response = final_client.get("/api/auth/profile/")
    assert profile_response.status_code == 200
    assert profile_response.data["username"] == staff_username