# Generated by Django 5.0.1 on 2025-10-11 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='여행명')),
                ('destination', models.CharField(max_length=200, verbose_name='목적지')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('status', models.CharField(choices=[('planning', '계획 중'), ('ongoing', '진행 중'), ('completed', '완료')], default='planning', max_length=20, verbose_name='상태')),
                ('invite_code', models.CharField(blank=True, help_text='자동 생성되는 8자리 코드', max_length=8, unique=True, verbose_name='초대 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('manager', models.ForeignKey(blank=True, help_text='총괄담당자가 배정', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_trips', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '여행',
                'verbose_name_plural': '여행 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
