# Generated by Django 5.0.1 on 2025-10-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0003_alter_traveler_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='참가일시')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.traveler', verbose_name='참가자')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '여행 참가자',
                'verbose_name_plural': '여행 참가자 목록',
                'ordering': ['joined_date'],
                'unique_together': {('trip', 'traveler')},
            },
        ),
    ]
