# Generated by Django 5.0.1 on 2025-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_tripparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="geofence_center_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="지도상 기준점을 지정합니다. 비워두면 위치 경보를 끕니다.",
                max_digits=9,
                null=True,
                verbose_name="지오펜스 위도",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="geofence_center_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="경도 좌표.",
                max_digits=9,
                null=True,
                verbose_name="지오펜스 경도",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="geofence_radius_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="참가자가 이 반경을 벗어나면 경보를 생성합니다.",
                max_digits=5,
                null=True,
                verbose_name="허용 반경(km)",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="heart_rate_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="이 값보다 높으면 경고를 발생시킵니다.",
                null=True,
                verbose_name="최대 심박수",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="heart_rate_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="이 값보다 낮으면 경고를 발생시킵니다. 비워두면 검사하지 않습니다.",
                null=True,
                verbose_name="최소 심박수",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="spo2_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="산소포화도(%)가 기준보다 낮을 때 경고를 발송합니다.",
                max_digits=5,
                null=True,
                verbose_name="최소 산소포화도",
            ),
        ),
    ]
