# Generated by Django 5.0.1 on 2025-10-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_geofence_center_lat_trip_geofence_center_lng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="신청 가능한 참가자 상한. 비워두면 제한이 없습니다.",
                null=True,
                verbose_name="최대 참가 인원",
            ),
        ),
    ]
