# Generated by Django 5.0.1 on 2025-10-11 12:26

import django.db.models.deletion
import schedules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_tripparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 문화재, 음식점, 자연', max_length=50, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, help_text='카테고리에 대한 설명', null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '장소 카테고리',
                'verbose_name_plural': '장소 카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 경복궁', max_length=200, verbose_name='장소명')),
                ('address', models.CharField(blank=True, help_text='예: 서울특별시 종로구 사직로', max_length=300, null=True, verbose_name='주소')),
                ('entrance_fee', models.IntegerField(blank=True, default=0, help_text='무료인 경우 0 또는 빈칸, 예: 3000 (3,000원)', null=True, verbose_name='입장료 (원)')),
                ('activity_time', models.DurationField(blank=True, help_text='예: 2시간 30분 → 2:30:00 형식 입력', null=True, verbose_name='권장 활동 시간')),
                ('ai_alternative_place', models.JSONField(blank=True, default=dict, help_text='JSON 형식: {"place_name": "장소명", "reason": "추천 이유"}', null=True, verbose_name='AI 추천 대체 장소')),
                ('ai_generated_info', models.TextField(blank=True, help_text='AI가 생성한 유용한 정보\n예: 봄철 벚꽃 명소, 주말 혼잡도 높음', null=True, verbose_name='AI 자동생성 관련 정보')),
                ('ai_meeting_point', models.CharField(blank=True, help_text='AI가 추천하는 장소\n예: 광화문 광장 세종대왕 동상 앞', max_length=200, null=True, verbose_name='AI 집결지 추천')),
                ('image', models.ImageField(blank=True, help_text='JPG, PNG 파일 업로드 가능', null=True, upload_to=schedules.models.place_image_path, verbose_name='장소 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(blank=True, help_text='장소 카테고리 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='schedules.placecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '장소',
                'verbose_name_plural': '장소 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='1일차, 2일차...', verbose_name='일차')),
                ('start_time', models.TimeField(help_text='예: 09:00', verbose_name='시작 시간')),
                ('end_time', models.TimeField(help_text='예: 12:00', verbose_name='종료 시간')),
                ('transport', models.CharField(blank=True, help_text='예: 단체버스, 기차, 도보', max_length=50, null=True, verbose_name='이동 수단')),
                ('main_content', models.TextField(blank=True, help_text='예: 숭례문 문화 해설 투어', null=True, verbose_name='주요 활동 내용')),
                ('meeting_point', models.CharField(blank=True, help_text='예: 숭례문 주차장', max_length=200, null=True, verbose_name='집결지')),
                ('budget', models.IntegerField(blank=True, default=0, help_text='예: 100000', null=True, verbose_name='예상 비용(원화)')),
                ('order', models.IntegerField(default=0, help_text='같은 날 내 순서 (1, 2, 3...)', verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedules.place', verbose_name='방문 장소')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'ordering': ['day_number', 'order', 'start_time'],
                'unique_together': {('trip', 'day_number', 'order')},
            },
        ),
    ]
