# Generated by Django 5.0.1 on 2025-10-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 가이드, 통역사, 코디네이터', max_length=50, unique=True, verbose_name='역할명')),
                ('description', models.TextField(blank=True, help_text='역할에 대한 설명', null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '담당자 역할',
                'verbose_name_plural': '담당자 역할 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='담당자 이름', max_length=100, verbose_name='이름')),
                ('phone', models.CharField(help_text='예: 010-1234-5678', max_length=20, verbose_name='연락처')),
                ('note', models.TextField(blank=True, help_text='특별 요청사항, 근무 시간, 전문 분야 등\n예: 9시 출근, 영어/중국어 가능, 단체 할인 협의 가능', null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(help_text='담당할 장소 선택', on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='schedules.place', verbose_name='장소')),
                ('role', models.ForeignKey(help_text='담당자의 역할 선택 (가이드, 통역사 등)', on_delete=django.db.models.deletion.PROTECT, related_name='coordinators', to='schedules.coordinatorrole', verbose_name='역할')),
            ],
            options={
                'verbose_name': '장소 담당자',
                'verbose_name_plural': '장소 담당자 목록',
                'ordering': ['role__name', 'name'],
                'indexes': [models.Index(fields=['place', 'role'], name='schedules_p_place_i_106c0e_idx')],
            },
        ),
    ]
