# Generated by Django 5.0.1 on 2025-10-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_coordinatorrole_placecoordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='예: 한복 대여, 오디오 가이드, 기념품', max_length=100, verbose_name='항목명')),
                ('price', models.IntegerField(help_text='원화 기준, 예: 15000 (15,000원)', verbose_name='가격 (원)')),
                ('description', models.CharField(blank=True, help_text='상세 정보, 예: 2시간 기준, 1인당 가격, 사전 예약 필수', max_length=200, null=True, verbose_name='설명')),
                ('display_order', models.IntegerField(default=0, help_text='낮은 숫자가 먼저 표시됨, 같은 가격일 때 순서 조정용', verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(help_text='지출 항목이 적용되는 장소', on_delete=django.db.models.deletion.CASCADE, related_name='optional_expenses', to='schedules.place', verbose_name='장소')),
            ],
            options={
                'verbose_name': '선택적 지출 항목',
                'verbose_name_plural': '선택적 지출 항목 목록',
                'ordering': ['place', 'price', 'display_order'],
                'indexes': [models.Index(fields=['place', 'price'], name='schedules_o_place_i_97411a_idx')],
            },
        ),
    ]
