# Generated by Django 5.0.1 on 2025-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_optionalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration_minutes',
            field=models.IntegerField(blank=True, editable=False, help_text='시작 및 종료 시간 입력 시 자동 계산됨', null=True, verbose_name='소요 시간(분)'),
        ),
    ]
