
# Generated by Django 5.0.1 on 2025-10-20 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_place_google_place_id_place_google_synced_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceUpdateSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="예: 서울시 문화재청 블로그, 이용자 후기",
                        max_length=100,
                        verbose_name="출처 이름",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Perplexity에 전달한 실제 주소. 운영 팀이 직접 관리합니다.",
                        verbose_name="참고 URL",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="출처 활용 시 주의사항이나 핵심 키워드를 짧게 정리합니다.",
                        max_length=200,
                        verbose_name="비고",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
            ],
            options={
                "verbose_name": "장소 업데이트 출처",
                "verbose_name_plural": "장소 업데이트 출처 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlaceSummaryCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_lines",
                    models.JSONField(
                        default=list,
                        help_text="줄 단위 요약 문장을 배열로 저장합니다. UI는 순서를 그대로 사용합니다.",
                        verbose_name="생성된 줄 목록",
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list,
                        help_text="Validator를 통과한 출처 정보를 리스트로 보관합니다.",
                        verbose_name="출처 메타데이터",
                    ),
                ),
                (
                    "ai_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Perplexity 응답 전문(JSON)을 저장하여 재검증 시 활용합니다.",
                        verbose_name="AI 원본 응답",
                    ),
                ),
                (
                    "generator",
                    models.CharField(
                        default="perplexity",
                        help_text="어떤 AI 엔진이 응답을 생성했는지 기록합니다.",
                        max_length=50,
                        verbose_name="생성기 식별자",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Validator까지 통과한 응답이 저장된 시간입니다.",
                        null=True,
                        verbose_name="AI 생성 시각",
                    ),
                ),
                (
                    "cached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="동일 요청에 대해 재사용할 수 있는 기준 시각입니다 (기본 24시간).",
                        null=True,
                        verbose_name="캐시 저장 시각",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="요약 생성 요청을 수행한 직원 계정. 실패 시에도 마지막 성공 요청자를 유지합니다.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_summary_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성 요청자",
                    ),
                ),
                (
                    "place",
                    models.OneToOneField(
                        help_text="Place가 삭제되면 요약 카드도 함께 제거됩니다.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_card",
                        to="schedules.place",
                        verbose_name="대상 장소",
                    ),
                ),
            ],
            options={
                "verbose_name": "장소 요약 카드",
                "verbose_name_plural": "장소 요약 카드 목록",
            },
        ),
        migrations.CreateModel(
            name="PlaceUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="예: 봄 시즌 야간 개장, 주차장 공사 안내",
                        max_length=100,
                        verbose_name="업데이트 제목",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="줄바꿈 포함 가능. 요약 생성 시 한 줄로 축약됩니다.",
                        verbose_name="상세 설명",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="안내 문구의 공식/비공식 출처 주소",
                        verbose_name="근거 URL",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        help_text="원본 공지/소식이 게시된 시간. 14일 경과 시 경고가 표시됩니다.",
                        verbose_name="발행일시",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="관공서·공식 홈페이지 등 1차 출처라면 체크합니다.",
                        verbose_name="공식 출처 여부",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        help_text="최신 소식이 적용되는 장소",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_updates",
                        to="schedules.place",
                        verbose_name="대상 장소",
                    ),
                ),
                (
                    "summary_card",
                    models.ForeignKey(
                        help_text="요약 카드 삭제 시 연관된 업데이트도 함께 제거됩니다.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="schedules.placesummarycard",
                        verbose_name="대상 요약 카드",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        help_text="줄(라인)과 매핑되는 참고 URL. 중복 입력을 막기 위해 테이블로 분리했습니다.",
                        related_name="updates",
                        to="schedules.placeupdatesource",
                        verbose_name="추가 참조 출처",
                    ),
                ),
            ],
            options={
                "verbose_name": "장소 최신 소식",
                "verbose_name_plural": "장소 최신 소식 목록",
                "ordering": ["-published_at"],
            },
        ),
    ]