# Generated by Django 5.0.1 on 2025-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_placeupdatesource_placesummarycard_placeupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="minimum_stay_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="일정 시간 재배치 시 보장해야 하는 최소 체류 시간",
                null=True,
                verbose_name="최소 체류 시간(분)",
            ),
        ),
    ]
